# Make file for compiling and loadable module B2R2

obj- := b2r2.o	# Dummy rule to force built-in.o to be made

obj-$(CONFIG_FB_B2R2) += b2r2.o

obj-$(CONFIG_FB_B2R2) += b2r2_array.o

obj-$(CONFIG_FB_B2R2) += b2r2_driver.o






