# U8500 Platform Support

snd-soc-u8500-objs := u8500_pcm.o u8500_msp_dai.o
snd-soc-u8500-ab3550-objs := mop500_ab3550.o

obj-$(CONFIG_SND_SOC_U8500) += snd-soc-u8500.o
obj-$(CONFIG_SND_SOC_AB3550) += snd-soc-u8500-ab3550.o





