# Make file for compiling and loadable module HDMI

obj- := av8100.o       # Dummy rule to force built-in.o to be made

obj-$(CONFIG_FB_HDMI) += av8100.o

clean-files := av8100.o built-in.o modules.order

