# Ux500 Platform Support

snd-soc-ux500-objs := ux500_pcm.o ux500_msp_dai.o
snd-soc-ux500-ab3550-objs := ux500_ab3550.o
snd-soc-ux500-cg29xx-objs := ux500_cg29xx.o

obj-$(CONFIG_SND_SOC_UX500) += snd-soc-ux500.o
obj-$(CONFIG_SND_SOC_UX500_AB3550) += snd-soc-ux500-ab3550.o
obj-$(CONFIG_SND_SOC_UX500_CG29XX) += snd-soc-ux500-cg29xx.o
